### ISSUE TITLE
Опции пустого тайтла и сброса.

### ISSUE THREAD

**Issue by ghost** [edbond88/nselect#1]
Не могу сделать так, чтобы у `<select>`  было пусто при загрузке. 
Если ставишь пробел `data-title=" "` то `<select>` не отображается.

Нет (или я не нашел) опции сброса выбора.

**Comment by edbond88** [comment]
1. Если поставить `data-title=" "`, то все отобразится, просто для блока `.nselect__head` нужно задать стили для отображения - высоту и ширину, т.к. если блок пустой, то его не видно. Я поправил в дефолтной теме `orange`, и добавил туда фиксированную высоту.
2. Попробуй примерно такую структуру:

``` html
<select class="nselect" name="pets">
    <option value="">Выберите животного</option>
    <option value="2">Dog</option>
    <option value="3">Frog</option>
    <option value="4">Duck</option>
    <option value="5">Elephant</option>
</select>
```

``` js
$('.nselect').nSelect({
    hideAfterSelect : true
});
```
